import 'package:app_cdi/models/models.dart';
import 'package:excel/excel.dart';
import 'package:flutter/material.dart';

class CDI2Provider extends ChangeNotifier {
  List<Palabra> palabrasSeccion1 = [
    Palabra(nombre: '¡Am!', icplim: false, subrayada: false),
    Palabra(nombre: '¡Auch!', icplim: true, subrayada: true),
    Palabra(nombre: '¡Ay!', icplim: false, subrayada: true),
    Palabra(nombre: 'Bee / me', icplim: false, subrayada: true),
    Palabra(nombre: 'Chuu-chuu', icplim: true, subrayada: true),
    Palabra(nombre: 'Cua-cuá', icplim: false, subrayada: true),
    Palabra(nombre: 'Gordogordo', icplim: true, subrayada: true),
    Palabra(nombre: 'Grrr', icplim: true, subrayada: true),
    Palabra(nombre: 'Gua-guá', icplim: false, subrayada: true),
    Palabra(nombre: 'Miau', icplim: false, subrayada: true),
    Palabra(nombre: 'Mmmmm', icplim: true, subrayada: true),
    Palabra(nombre: 'Muu', icplim: false, subrayada: true),
    Palabra(nombre: 'Oinc-oinc', icplim: true, subrayada: true),
    Palabra(nombre: '¡Pazz!', icplim: true, subrayada: true),
    Palabra(nombre: '¡Pío-pío!', icplim: false, subrayada: true),
    Palabra(nombre: 'Pi-pí', icplim: false, subrayada: false),
    Palabra(nombre: '¡Pum!', icplim: false, subrayada: false),
    Palabra(nombre: 'Qui-qui-ri-quí', icplim: false, subrayada: true),
    Palabra(nombre: 'Tic-tac', icplim: true, subrayada: true),
    Palabra(nombre: 'Tu-tú', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion2 = [
    Palabra(nombre: 'Abeja', icplim: false, subrayada: true),
    Palabra(nombre: 'Águila', icplim: true, subrayada: true),
    Palabra(nombre: 'Alacrán', icplim: true, subrayada: true),
    Palabra(nombre: 'Animal', icplim: false, subrayada: true),
    Palabra(nombre: 'Araña', icplim: false, subrayada: true),
    Palabra(nombre: 'Ardilla', icplim: false, subrayada: true),
    Palabra(nombre: 'Ballena', icplim: true, subrayada: true),
    Palabra(nombre: 'Bicho', icplim: false, subrayada: false),
    Palabra(nombre: 'Borrego', icplim: false, subrayada: true),
    Palabra(nombre: 'Buey', icplim: false, subrayada: false),
    Palabra(nombre: 'Búho', icplim: false, subrayada: false),
    Palabra(nombre: 'Burro', icplim: false, subrayada: false),
    Palabra(nombre: 'Caballo', icplim: false, subrayada: true),
    Palabra(nombre: 'Canario', icplim: true, subrayada: true),
    Palabra(nombre: 'Cangrejo', icplim: true, subrayada: true),
    Palabra(nombre: 'Caracol', icplim: true, subrayada: true),
    Palabra(nombre: 'Cebra', icplim: false, subrayada: false),
    Palabra(nombre: 'Cocodrilo', icplim: false, subrayada: true),
    Palabra(nombre: 'Conejo', icplim: false, subrayada: true),
    Palabra(nombre: 'Elefante', icplim: false, subrayada: true),
    Palabra(nombre: 'Foca', icplim: false, subrayada: false),
    Palabra(nombre: 'Gallina', icplim: false, subrayada: false),
    Palabra(nombre: 'Ganso', icplim: false, subrayada: true),
    Palabra(nombre: 'Gato', icplim: false, subrayada: true),
    Palabra(nombre: 'Guajolote', icplim: false, subrayada: true),
    Palabra(nombre: 'Gusano/lombriz', icplim: true, subrayada: true),
    Palabra(nombre: 'Hipopótamo', icplim: false, subrayada: false),
    Palabra(nombre: 'Hormiga', icplim: false, subrayada: true),
    Palabra(nombre: 'Jirafa', icplim: false, subrayada: true),
    Palabra(nombre: 'Oso', icplim: false, subrayada: true),
    Palabra(nombre: 'León', icplim: false, subrayada: true),
    Palabra(nombre: 'Lobo', icplim: false, subrayada: true),
    Palabra(nombre: 'Mariposa', icplim: false, subrayada: true),
    Palabra(nombre: 'Mono', icplim: false, subrayada: true),
    Palabra(nombre: 'Mosca', icplim: false, subrayada: true),
    Palabra(nombre: 'Mosco', icplim: false, subrayada: true),
    Palabra(nombre: 'Paloma', icplim: true, subrayada: true),
    Palabra(nombre: 'Pájaro', icplim: false, subrayada: true),
    Palabra(nombre: 'Panda', icplim: true, subrayada: true),
    Palabra(nombre: 'Pato', icplim: false, subrayada: true),
    Palabra(nombre: 'Perico', icplim: true, subrayada: true),
    Palabra(nombre: 'Perro', icplim: false, subrayada: true),
    Palabra(nombre: 'Pescado', icplim: false, subrayada: true),
    Palabra(nombre: 'Pingüino', icplim: false, subrayada: true),
    Palabra(nombre: 'Pollito', icplim: false, subrayada: true),
    Palabra(nombre: 'Puerco', icplim: false, subrayada: true),
    Palabra(nombre: 'Rana', icplim: false, subrayada: true),
    Palabra(nombre: 'Rata', icplim: true, subrayada: true),
    Palabra(nombre: 'Ratón/hámster', icplim: false, subrayada: true),
    Palabra(nombre: 'Tiburón', icplim: true, subrayada: true),
    Palabra(nombre: 'Tigre', icplim: false, subrayada: true),
    Palabra(nombre: 'Toro', icplim: true, subrayada: true),
    Palabra(nombre: 'Tortuga', icplim: false, subrayada: true),
    Palabra(nombre: 'Vaca', icplim: false, subrayada: true),
    Palabra(nombre: 'Venado', icplim: false, subrayada: true),
    Palabra(nombre: 'Víbora', icplim: false, subrayada: false),
    Palabra(nombre: 'Zorro', icplim: true, subrayada: true),
  ];

  List<Palabra> palabrasSeccion3 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion4 = [
    Palabra(nombre: 'Agua', icplim: false, subrayada: true),
    Palabra(nombre: 'Arroz', icplim: false, subrayada: true),
    Palabra(nombre: 'Atole', icplim: false, subrayada: true),
    Palabra(nombre: 'Atún', icplim: false, subrayada: false),
    Palabra(nombre: 'Avena', icplim: true, subrayada: true),
    Palabra(nombre: 'Azúcar', icplim: false, subrayada: true),
    Palabra(nombre: 'Cacahuate/maní', icplim: false, subrayada: false),
    Palabra(nombre: 'Café', icplim: false, subrayada: true),
    Palabra(nombre: 'Calabaza', icplim: false, subrayada: false),
    Palabra(nombre: 'Carne', icplim: false, subrayada: true),
    Palabra(nombre: 'Cereal', icplim: false, subrayada: true),
    Palabra(nombre: 'Chícharo', icplim: false, subrayada: false),
    Palabra(nombre: 'Chicharrón', icplim: true, subrayada: true),
    Palabra(nombre: 'Chicle', icplim: false, subrayada: true),
    Palabra(nombre: 'Chile', icplim: false, subrayada: true),
    Palabra(nombre: 'Chocolate', icplim: false, subrayada: true),
    Palabra(nombre: 'Comida', icplim: false, subrayada: true),
    Palabra(nombre: 'Crema de cacahuate', icplim: false, subrayada: false),
    Palabra(nombre: 'Dulce', icplim: false, subrayada: true),
    Palabra(nombre: 'Durazno', icplim: false, subrayada: false),
    Palabra(nombre: 'Ejotes', icplim: false, subrayada: false),
    Palabra(nombre: 'Elote', icplim: false, subrayada: false),
    Palabra(nombre: 'Espagueti', icplim: false, subrayada: false),
    Palabra(nombre: 'Fresa', icplim: false, subrayada: true),
    Palabra(nombre: 'Frijoles', icplim: false, subrayada: true),
    Palabra(nombre: 'Galleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Gelatina', icplim: false, subrayada: true),
    Palabra(nombre: 'Hamburguesa', icplim: false, subrayada: true),
    Palabra(nombre: 'Helado/nieve', icplim: false, subrayada: true),
    Palabra(nombre: 'Hielo', icplim: false, subrayada: false),
    Palabra(nombre: 'Hot cakes', icplim: false, subrayada: false),
    Palabra(nombre: 'Huevo', icplim: false, subrayada: true),
    Palabra(nombre: 'Jamón', icplim: false, subrayada: true),
    Palabra(nombre: 'Jugo', icplim: false, subrayada: true),
    Palabra(nombre: 'Leche', icplim: false, subrayada: true),
    Palabra(nombre: 'Licuado', icplim: false, subrayada: false),
    Palabra(nombre: 'Limonada', icplim: false, subrayada: false),
    Palabra(nombre: 'Limón', icplim: true, subrayada: true),
    Palabra(nombre: 'Mango', icplim: true, subrayada: true),
    Palabra(nombre: 'Mantequilla', icplim: false, subrayada: true),
    Palabra(nombre: 'Manzana', icplim: false, subrayada: true),
    Palabra(nombre: 'Melón', icplim: false, subrayada: false),
    Palabra(nombre: 'Mermelada', icplim: false, subrayada: false),
    Palabra(nombre: 'Miel', icplim: true, subrayada: true),
    Palabra(nombre: 'Naranja', icplim: false, subrayada: true),
    Palabra(nombre: 'Paleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Palomitas', icplim: false, subrayada: true),
    Palabra(nombre: 'Pan', icplim: false, subrayada: true),
    Palabra(nombre: 'Pan dulce', icplim: false, subrayada: false),
    Palabra(nombre: 'Papas', icplim: false, subrayada: true),
    Palabra(nombre: 'Papitas/frituras', icplim: false, subrayada: false),
    Palabra(nombre: 'Pasas', icplim: false, subrayada: false),
    Palabra(nombre: 'Pastel', icplim: false, subrayada: true),
    Palabra(nombre: 'Pescado', icplim: false, subrayada: true),
    Palabra(nombre: 'Piña', icplim: true, subrayada: true),
    Palabra(nombre: 'Pizza', icplim: true, subrayada: true),
    Palabra(nombre: 'Plátano/bananas', icplim: false, subrayada: true),
    Palabra(nombre: 'Pollo', icplim: false, subrayada: true),
    Palabra(nombre: 'Quesadilla', icplim: false, subrayada: true),
    Palabra(nombre: 'Queso', icplim: false, subrayada: true),
    Palabra(nombre: 'Refresco/soda', icplim: false, subrayada: true),
    Palabra(nombre: 'Sal', icplim: false, subrayada: false),
    Palabra(nombre: 'Salchicha', icplim: false, subrayada: true),
    Palabra(nombre: 'Salsa', icplim: false, subrayada: false),
    Palabra(nombre: 'Sandía', icplim: false, subrayada: false),
    Palabra(nombre: 'Sándwich', icplim: true, subrayada: true),
    Palabra(nombre: 'Sopa', icplim: false, subrayada: true),
    Palabra(nombre: 'Tacos', icplim: false, subrayada: true),
    Palabra(nombre: 'Té', icplim: false, subrayada: false),
    Palabra(nombre: 'Torta', icplim: false, subrayada: true),
    Palabra(nombre: 'Tortilla', icplim: false, subrayada: true),
    Palabra(nombre: 'Uvas', icplim: false, subrayada: true),
    Palabra(nombre: 'Vainilla', icplim: false, subrayada: false),
    Palabra(nombre: 'Verduras', icplim: true, subrayada: true),
    Palabra(nombre: 'Vitaminas', icplim: false, subrayada: false),
    Palabra(nombre: 'Yogur', icplim: false, subrayada: true),
    Palabra(nombre: 'Zanahoria', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion5 = [
    Palabra(nombre: 'Abrigo', icplim: false, subrayada: true),
    Palabra(nombre: 'Aretes', icplim: false, subrayada: false),
    Palabra(nombre: 'Babero', icplim: false, subrayada: true),
    Palabra(nombre: 'Bolsa', icplim: false, subrayada: true),
    Palabra(nombre: 'Botas', icplim: false, subrayada: true),
    Palabra(nombre: 'Botón', icplim: false, subrayada: true),
    Palabra(nombre: 'Bufanda', icplim: false, subrayada: true),
    Palabra(nombre: 'Calceta/calcetín', icplim: false, subrayada: true),
    Palabra(nombre: 'Calzón', icplim: false, subrayada: true),
    Palabra(nombre: 'Camisa', icplim: false, subrayada: true),
    Palabra(nombre: 'Camiseta', icplim: true, subrayada: true),
    Palabra(nombre: 'Chaleco', icplim: true, subrayada: true),
    Palabra(nombre: 'Chamarra', icplim: true, subrayada: true),
    Palabra(nombre: 'Chancla/sandalia', icplim: false, subrayada: true),
    Palabra(nombre: 'Cierre', icplim: false, subrayada: true),
    Palabra(nombre: 'Collar', icplim: false, subrayada: true),
    Palabra(nombre: 'Falda', icplim: false, subrayada: true),
    Palabra(nombre: 'Gorra', icplim: false, subrayada: true),
    Palabra(nombre: 'Guantes', icplim: false, subrayada: true),
    Palabra(nombre: 'Lentes', icplim: false, subrayada: true),
    Palabra(nombre: 'Medias', icplim: false, subrayada: false),
    Palabra(nombre: 'Pantalón', icplim: false, subrayada: true),
    Palabra(nombre: 'Pañal', icplim: false, subrayada: false),
    Palabra(nombre: 'Pijama', icplim: false, subrayada: true),
    Palabra(nombre: 'Playera', icplim: false, subrayada: true),
    Palabra(nombre: 'Ropa', icplim: false, subrayada: false),
    Palabra(nombre: 'Shorts', icplim: false, subrayada: true),
    Palabra(nombre: 'Sombrero', icplim: false, subrayada: true),
    Palabra(nombre: 'Sudadera', icplim: true, subrayada: true),
    Palabra(nombre: 'Suéter', icplim: false, subrayada: true),
    Palabra(nombre: 'Tenis', icplim: true, subrayada: true),
    Palabra(nombre: 'Vestido', icplim: false, subrayada: true),
    Palabra(nombre: 'Zapato', icplim: false, subrayada: true),
  ];

  List<Palabra> palabrasSeccion6 = [
    Palabra(nombre: 'Barba', icplim: false, subrayada: false),
    Palabra(nombre: 'Bigote', icplim: false, subrayada: false),
    Palabra(nombre: 'Boca', icplim: false, subrayada: true),
    Palabra(nombre: 'Brazo', icplim: false, subrayada: true),
    Palabra(nombre: 'Cabeza', icplim: false, subrayada: true),
    Palabra(nombre: 'Caca/popo', icplim: true, subrayada: true),
    Palabra(nombre: 'Cachete', icplim: false, subrayada: true),
    Palabra(nombre: 'Cara', icplim: false, subrayada: true),
    Palabra(nombre: 'Ceja', icplim: true, subrayada: true),
    Palabra(nombre: 'Chichi/pecho', icplim: false, subrayada: true),
    Palabra(nombre: 'Chis/pipi', icplim: true, subrayada: true),
    Palabra(nombre: 'Cola', icplim: true, subrayada: true),
    Palabra(nombre: 'Dedo', icplim: false, subrayada: true),
    Palabra(nombre: 'Dientes', icplim: false, subrayada: true),
    Palabra(nombre: 'Garganta/anginas', icplim: false, subrayada: false),
    Palabra(nombre: 'Hombro', icplim: false, subrayada: false),
    Palabra(nombre: 'Labios', icplim: false, subrayada: true),
    Palabra(nombre: 'Lengua', icplim: false, subrayada: true),
    Palabra(nombre: 'Mano', icplim: false, subrayada: true),
    Palabra(nombre: 'Nalgas/pompas', icplim: false, subrayada: true),
    Palabra(nombre: 'Nariz', icplim: false, subrayada: true),
    Palabra(nombre: 'Ojos', icplim: false, subrayada: true),
    Palabra(nombre: 'Ombligo', icplim: false, subrayada: true),
    Palabra(nombre: 'Oreja', icplim: false, subrayada: true),
    Palabra(nombre: 'Panza', icplim: false, subrayada: true),
    Palabra(nombre: 'Pelo/cabello', icplim: false, subrayada: true),
    Palabra(nombre: 'Pene', icplim: false, subrayada: false),
    Palabra(nombre: 'Pestañas', icplim: true, subrayada: true),
    Palabra(nombre: 'Piernas', icplim: false, subrayada: true),
    Palabra(nombre: 'Pies', icplim: false, subrayada: true),
    Palabra(nombre: 'Rodilla', icplim: false, subrayada: false),
    Palabra(nombre: 'Uña', icplim: true, subrayada: true),
    Palabra(nombre: 'Vagina', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion7 = [
    Palabra(nombre: 'Andadera', icplim: true, subrayada: true),
    Palabra(nombre: 'Bat', icplim: false, subrayada: false),
    Palabra(nombre: 'Burbujas', icplim: false, subrayada: false),
    Palabra(nombre: 'Colores', icplim: false, subrayada: true),
    Palabra(nombre: 'Crayolas', icplim: false, subrayada: true),
    Palabra(nombre: 'Cubo', icplim: true, subrayada: true),
    Palabra(nombre: 'Cuento', icplim: true, subrayada: true),
    Palabra(nombre: 'Globo/bomba', icplim: false, subrayada: true),
    Palabra(nombre: 'Hoja/papel', icplim: false, subrayada: true),
    Palabra(nombre: 'Juego de té', icplim: true, subrayada: true),
    Palabra(nombre: 'Juguete', icplim: false, subrayada: true),
    Palabra(nombre: 'Lápiz', icplim: false, subrayada: true),
    Palabra(nombre: 'Libro', icplim: false, subrayada: true),
    Palabra(nombre: 'Muñeca/o', icplim: false, subrayada: true),
    Palabra(nombre: 'Osito', icplim: false, subrayada: true),
    Palabra(nombre: 'Patines', icplim: false, subrayada: false),
    Palabra(nombre: 'Pelota', icplim: false, subrayada: true),
    Palabra(nombre: 'Peluche', icplim: false, subrayada: true),
    Palabra(nombre: 'Pinturas', icplim: false, subrayada: true),
    Palabra(nombre: 'Piñata', icplim: true, subrayada: true),
    Palabra(nombre: 'Pistola', icplim: true, subrayada: true),
    Palabra(nombre: 'Plastilina', icplim: false, subrayada: true),
    Palabra(nombre: 'Pluma/plumones', icplim: false, subrayada: true),
    Palabra(nombre: 'Robot', icplim: true, subrayada: true),
    Palabra(nombre: 'Tambor', icplim: false, subrayada: true),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trompo', icplim: true, subrayada: true),
    Palabra(nombre: 'Yoyo', icplim: true, subrayada: true),
  ];

  List<Palabra> palabrasSeccion8 = [
    Palabra(nombre: 'Almohada', icplim: false, subrayada: true),
    Palabra(nombre: 'Aspiradora', icplim: false, subrayada: false),
    Palabra(nombre: 'Basura', icplim: false, subrayada: true),
    Palabra(nombre: 'Bolsa', icplim: false, subrayada: false),
    Palabra(nombre: 'Bote', icplim: true, subrayada: true),
    Palabra(nombre: 'Botella/mamila', icplim: false, subrayada: true),
    Palabra(nombre: 'Caja', icplim: false, subrayada: true),
    Palabra(nombre: 'Cámara', icplim: false, subrayada: false),
    Palabra(nombre: 'Canasta', icplim: false, subrayada: false),
    Palabra(nombre: 'Casete', icplim: false, subrayada: false),
    Palabra(nombre: 'Cepillo', icplim: false, subrayada: true),
    Palabra(nombre: 'Cepillo de dientes', icplim: false, subrayada: true),
    Palabra(nombre: 'Cerillos', icplim: false, subrayada: false),
    Palabra(nombre: 'Chupón/chupete', icplim: false, subrayada: true),
    Palabra(nombre: 'Cigarros', icplim: false, subrayada: false),
    Palabra(nombre: 'Clavo', icplim: false, subrayada: false),
    Palabra(nombre: 'Cobija', icplim: false, subrayada: true),
    Palabra(nombre: 'Cortina', icplim: true, subrayada: true),
    Palabra(nombre: 'Cuadro', icplim: false, subrayada: true),
    Palabra(nombre: 'Cubeta', icplim: false, subrayada: false),
    Palabra(nombre: 'Cuchara', icplim: false, subrayada: true),
    Palabra(nombre: 'Cuchillo', icplim: false, subrayada: true),
    Palabra(nombre: 'Dinero', icplim: false, subrayada: true),
    Palabra(nombre: 'Escoba', icplim: false, subrayada: true),
    Palabra(nombre: 'Espejo', icplim: false, subrayada: true),
    Palabra(nombre: 'Foco', icplim: true, subrayada: true),
    Palabra(nombre: 'Fotos', icplim: false, subrayada: true),
    Palabra(nombre: 'Jabón', icplim: false, subrayada: true),
    Palabra(nombre: 'Jaula', icplim: true, subrayada: true),
    Palabra(nombre: 'Lámpara', icplim: false, subrayada: true),
    Palabra(nombre: 'Llave', icplim: false, subrayada: true),
    Palabra(nombre: 'Luz', icplim: false, subrayada: false),
    Palabra(nombre: 'Martillo', icplim: false, subrayada: false),
    Palabra(nombre: 'Medicina', icplim: false, subrayada: true),
    Palabra(nombre: 'Mochila', icplim: true, subrayada: true),
    Palabra(nombre: 'Olla', icplim: false, subrayada: false),
    Palabra(nombre: 'Pañuelo', icplim: false, subrayada: false),
    Palabra(nombre: 'Papel', icplim: false, subrayada: true),
    Palabra(nombre: 'Peine', icplim: false, subrayada: true),
    Palabra(nombre: 'Pasta de dientes', icplim: false, subrayada: false),
    Palabra(nombre: 'Película', icplim: true, subrayada: true),
    Palabra(nombre: 'Periódico', icplim: false, subrayada: false),
    Palabra(nombre: 'Planca', icplim: false, subrayada: false),
    Palabra(nombre: 'Plato', icplim: false, subrayada: true),
    Palabra(nombre: 'Radio', icplim: false, subrayada: false),
    Palabra(nombre: 'Reloj', icplim: false, subrayada: true),
    Palabra(nombre: 'Servilleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Tapete', icplim: false, subrayada: false),
    Palabra(nombre: 'Taza', icplim: false, subrayada: true),
    Palabra(nombre: 'Teléfono', icplim: false, subrayada: true),
    Palabra(nombre: 'Tenedor', icplim: false, subrayada: true),
    Palabra(nombre: 'Tijeras', icplim: false, subrayada: true),
    Palabra(nombre: 'Toalla', icplim: false, subrayada: true),
    Palabra(nombre: 'Trapo', icplim: false, subrayada: true),
    Palabra(nombre: 'Vaso', icplim: false, subrayada: true),
    Palabra(nombre: 'Vela', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion9 = [
    Palabra(nombre: 'Alacena', icplim: true, subrayada: true),
    Palabra(nombre: 'Bacinica', icplim: false, subrayada: true),
    Palabra(nombre: 'Banco', icplim: false, subrayada: true),
    Palabra(nombre: 'Baño', icplim: false, subrayada: true),
    Palabra(nombre: 'Cajón', icplim: false, subrayada: false),
    Palabra(nombre: 'Cama', icplim: false, subrayada: true),
    Palabra(nombre: 'Champú', icplim: false, subrayada: true),
    Palabra(nombre: 'Cochera/garaje', icplim: false, subrayada: false),
    Palabra(nombre: 'Cocina', icplim: false, subrayada: true),
    Palabra(nombre: 'Comedor', icplim: true, subrayada: true),
    Palabra(nombre: 'Computadora', icplim: false, subrayada: false),
    Palabra(nombre: 'Cuarto', icplim: false, subrayada: false),
    Palabra(nombre: 'Cuna', icplim: false, subrayada: true),
    Palabra(nombre: 'Escaleras', icplim: false, subrayada: true),
    Palabra(nombre: 'Escritorio', icplim: true, subrayada: true),
    Palabra(nombre: 'Estufa', icplim: false, subrayada: true),
    Palabra(nombre: 'Horno', icplim: false, subrayada: true),
    Palabra(nombre: 'Lavabo', icplim: false, subrayada: true),
    Palabra(nombre: 'Lavadora', icplim: false, subrayada: false),
    Palabra(nombre: 'Librero', icplim: false, subrayada: true),
    Palabra(nombre: 'Mesa', icplim: false, subrayada: true),
    Palabra(nombre: 'Mueble', icplim: false, subrayada: false),
    Palabra(nombre: 'Patio', icplim: false, subrayada: false),
    Palabra(nombre: 'Puerta', icplim: false, subrayada: true),
    Palabra(nombre: 'Recámara', icplim: false, subrayada: true),
    Palabra(nombre: 'Refrigerador', icplim: false, subrayada: true),
    Palabra(nombre: 'Regadera/ducha', icplim: false, subrayada: false),
    Palabra(nombre: 'Ropero/clóset', icplim: false, subrayada: true),
    Palabra(nombre: 'Sala', icplim: false, subrayada: true),
    Palabra(nombre: 'Secadora', icplim: false, subrayada: false),
    Palabra(nombre: 'Silla', icplim: false, subrayada: true),
    Palabra(nombre: 'Sillón', icplim: false, subrayada: true),
    Palabra(nombre: 'Sofá', icplim: false, subrayada: true),
    Palabra(nombre: 'Televisión', icplim: false, subrayada: true),
    Palabra(nombre: 'Tina', icplim: false, subrayada: false),
    Palabra(nombre: 'Ventana', icplim: false, subrayada: true),
  ];

  List<Palabra> palabrasSeccion10 = [
    Palabra(nombre: 'Alberca/piscina', icplim: false, subrayada: true),
    Palabra(nombre: 'Árbol', icplim: false, subrayada: true),
    Palabra(nombre: 'Bandera', icplim: false, subrayada: true),
    Palabra(nombre: 'Cielo', icplim: false, subrayada: true),
    Palabra(nombre: 'Coladera', icplim: false, subrayada: false),
    Palabra(nombre: 'Columpio', icplim: false, subrayada: false),
    Palabra(nombre: 'Estrella', icplim: false, subrayada: true),
    Palabra(nombre: 'Flor', icplim: false, subrayada: true),
    Palabra(nombre: 'Fuego', icplim: false, subrayada: true),
    Palabra(nombre: 'Hojas', icplim: false, subrayada: false),
    Palabra(nombre: 'Leña', icplim: false, subrayada: false),
    Palabra(nombre: 'Lluvia', icplim: false, subrayada: true),
    Palabra(nombre: 'Luna', icplim: false, subrayada: true),
    Palabra(nombre: 'Maceta', icplim: false, subrayada: false),
    Palabra(nombre: 'Manguera', icplim: false, subrayada: false),
    Palabra(nombre: 'Muñeco de nieve', icplim: false, subrayada: false),
    Palabra(nombre: 'Nieve', icplim: false, subrayada: true),
    Palabra(nombre: 'Nube', icplim: false, subrayada: true),
    Palabra(nombre: 'Pala', icplim: false, subrayada: false),
    Palabra(nombre: 'Palo', icplim: false, subrayada: false),
    Palabra(nombre: 'Pasto', icplim: false, subrayada: true),
    Palabra(nombre: 'Piedra', icplim: false, subrayada: true),
    Palabra(nombre: 'Planta', icplim: false, subrayada: true),
    Palabra(nombre: 'Reja', icplim: false, subrayada: false),
    Palabra(nombre: 'Resbaladilla', icplim: false, subrayada: false),
    Palabra(nombre: 'Sol', icplim: false, subrayada: true),
    Palabra(nombre: 'Tanque', icplim: false, subrayada: false),
    Palabra(nombre: 'Techo', icplim: false, subrayada: false),
    Palabra(nombre: 'Tierra', icplim: false, subrayada: false),
    Palabra(nombre: 'Timbre', icplim: false, subrayada: false),
    Palabra(nombre: 'Viento/aire', icplim: false, subrayada: true),
  ];

  List<Palabra> palabrasSeccion11 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion12 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion13 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion14 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion15 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion16 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion17 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion18 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion19 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion20 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion21 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion22 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  List<Palabra> palabrasSeccion23 = [
    Palabra(nombre: 'Autobús', icplim: false, subrayada: true),
    Palabra(nombre: 'Avión', icplim: false, subrayada: true),
    Palabra(nombre: 'Barco', icplim: false, subrayada: true),
    Palabra(nombre: 'Bicicleta', icplim: false, subrayada: true),
    Palabra(nombre: 'Camión de bomberos', icplim: false, subrayada: false),
    Palabra(nombre: 'Camión', icplim: false, subrayada: true),
    Palabra(nombre: 'Camioneta', icplim: true, subrayada: true),
    Palabra(nombre: 'Carreola', icplim: false, subrayada: true),
    Palabra(nombre: 'Carro/Coche', icplim: false, subrayada: false),
    Palabra(nombre: 'Helicóptero', icplim: false, subrayada: true),
    Palabra(nombre: 'Lancha', icplim: true, subrayada: true),
    Palabra(nombre: 'Metro', icplim: true, subrayada: true),
    Palabra(nombre: 'Moto', icplim: false, subrayada: true),
    Palabra(nombre: 'Nave', icplim: true, subrayada: true),
    Palabra(nombre: 'Pesero', icplim: true, subrayada: true),
    Palabra(nombre: 'Taxi', icplim: true, subrayada: true),
    Palabra(nombre: 'Tractor', icplim: false, subrayada: false),
    Palabra(nombre: 'Tráiler', icplim: true, subrayada: true),
    Palabra(nombre: 'Tren', icplim: false, subrayada: false),
    Palabra(nombre: 'Triciclo', icplim: false, subrayada: false),
    Palabra(nombre: 'Trineo', icplim: false, subrayada: false),
  ];

  void setOpcionPalabra(Opcion opcion, Palabra palabra) {
    palabra.opcion = opcion;
    notifyListeners();
  }

  int getTotalC(List<Palabra> palabras) {
    int total = 0;
    for (var palabra in palabras) {
      if (palabra.subrayada && palabra.opcion == Opcion.comprende) total += 1;
    }
    return total;
  }

  int getTotalCD(List<Palabra> palabras) {
    int total = 0;
    for (var palabra in palabras) {
      if (palabra.subrayada && palabra.opcion == Opcion.comprendeYDice) {
        total += 1;
      }
    }
    return total;
  }

  int getTotalD(List<Palabra> palabras) {
    int total = 0;
    for (var palabra in palabras) {
      if (palabra.opcion == Opcion.comprendeYDice) {
        total += 1;
      }
    }
    return total;
  }

  Future<bool> generarReporteExcel(String bebeId) async {
    //Crear excel
    Excel excel = Excel.createExcel();

    List<String> nombreSheets = [
      'ONOMATOPEYAS',
      'ANIMALES',
      'VEHICULOS',
      'ALIMENTOS',
      'ROPA',
      'CUERPO',
      'JUGUETES',
      'ART. HOGAR',
      'MUEBLES',
      'HOGAR',
    ];

    for (var nombre in nombreSheets) {
      excel.copy(excel.getDefaultSheet() ?? 'Sheet1', nombre);
    }

    List<Sheet?> sheets = [];

    excel.delete(excel.getDefaultSheet() ?? 'Sheet1');

    for (var nombre in nombreSheets) {
      sheets.add(excel.sheets[nombre]);
    }

    //1
    List<String> nombresSeccion1 =
        palabrasSeccion1.map((e) => e.nombre).toList();

    List<dynamic> row = [];

    for (var palabra in palabrasSeccion1) {
      int coding = 0;
      if (palabra.opcion == Opcion.comprende) {
        coding = 1;
      } else if (palabra.opcion == Opcion.comprendeYDice) {
        coding = 2;
      }
      row.add(coding);
    }

    sheets[0]!.appendRow(['ID', ...nombresSeccion1]);
    sheets[0]!.appendRow([bebeId, ...row]);

    //Descargar
    final List<int>? fileBytes = excel.save(fileName: "resultados.xlsx");
    if (fileBytes == null) return false;

    return true;
  }
}
